# Site settings
title: Zolomon.com
email: zolomon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Functional programming, game development, computer security,
  artificial intelligence, mathematics, art, animatics, music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zolomon.com" # the base hostname & protocol for your site
twitter_username: zolmn
github_username:  zolomon

# Build settings
markdown: kramdown
highlighter: rouge
